# Generated by Django 4.2.4 on 2023-09-20 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0002_contact_groupinfo_userinfo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerdetail',
            name='DraftKingsName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='playerdetail',
            name='FanDuelName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='playerdetail',
            name='FantasyDraftName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='playerdetail',
            name='UsaTodayHeadshotNoBackgroundUrl',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='playerdetail',
            name='UsaTodayHeadshotUrl',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='playerdetail',
            name='YahooName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
