# Generated by Django 4.2.4 on 2023-09-21 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0003_alter_playerdetail_draftkingsname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerdetail',
            name='DepthPosition',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='playerdetail',
            name='DepthPositionCategory',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='playerdetail',
            name='SportRadarPlayerID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
