# Generated by Django 4.2.4 on 2023-09-21 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0004_alter_playerdetail_depthposition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerdetail',
            name='BirthDateString',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
