# Generated by Django 4.2.4 on 2023-11-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0008_alter_ncaafteamcontactinfo_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='Key',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='TeamID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
