# Generated by Django 4.2.4 on 2023-11-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0010_alter_team_options_team_nfl_team_key_2aa1a0_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nflteamcontactinfo',
            name='ID',
        ),
        migrations.AddField(
            model_name='nflteamcontactinfo',
            name='Key',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nflteamcontactinfo',
            name='TeamID',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
