# Generated by Django 4.2.4 on 2023-11-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0011_remove_nflteamcontactinfo_id_nflteamcontactinfo_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ncaafteamcontactinfo',
            name='id',
        ),
        migrations.AddField(
            model_name='ncaafteamcontactinfo',
            name='TeamID',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
