# Generated by Django 4.2.4 on 2023-11-15 00:29

from django.db import migrations, models
import django.db.models.deletion
import nfl.models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0012_remove_ncaafteamcontactinfo_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestTable',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Text', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='contact',
            name='ContactLevel',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='ContactType',
        ),
        migrations.AddField(
            model_name='contact',
            name='Category',
            field=models.CharField(choices=[(nfl.models.ContactCategoryConstants['NFLPLAYER'], nfl.models.ContactCategoryConstants['NFLPLAYER']), (nfl.models.ContactCategoryConstants['NFLTEAM'], nfl.models.ContactCategoryConstants['NFLTEAM']), (nfl.models.ContactCategoryConstants['ORGANIZATION'], nfl.models.ContactCategoryConstants['ORGANIZATION']), (nfl.models.ContactCategoryConstants['INDIVIDUAL'], nfl.models.ContactCategoryConstants['INDIVIDUAL']), (nfl.models.ContactCategoryConstants['COLLEGETEAM'], nfl.models.ContactCategoryConstants['COLLEGETEAM'])], default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='DataID',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='Description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='Private',
            field=models.IntegerField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='OwnerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Addresses', to='nfl.subcontact'),
        ),
        migrations.AlterField(
            model_name='otherdetail',
            name='OwnerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OtherDetails', to='nfl.subcontact'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='OwnerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PhoneNumbers', to='nfl.subcontact'),
        ),
        migrations.AlterField(
            model_name='subcontact',
            name='Contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SubContacts', to='nfl.contact'),
        ),
    ]
