# Generated by Django 4.2.4 on 2023-11-16 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0014_alter_contact_category_alter_contact_private'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-Name']},
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['-Owner'], name='nfl_contact_Owner_d44eed_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['-Category'], name='nfl_contact_Categor_574e74_idx'),
        ),
    ]
