# Generated by Django 4.2.4 on 2023-11-16 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0015_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['Name']},
        ),
        migrations.AlterModelOptions(
            name='playerdetail',
            options={'ordering': ['Name']},
        ),
        migrations.AlterModelOptions(
            name='stadium',
            options={'ordering': ['Name']},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['Key']},
        ),
        migrations.RemoveIndex(
            model_name='contact',
            name='nfl_contact_Owner_d44eed_idx',
        ),
        migrations.RemoveIndex(
            model_name='contact',
            name='nfl_contact_Categor_574e74_idx',
        ),
        migrations.RemoveIndex(
            model_name='playerdetail',
            name='nfl_playerd_Name_5f081e_idx',
        ),
        migrations.RemoveIndex(
            model_name='stadium',
            name='nfl_stadium_Name_e3e749_idx',
        ),
        migrations.RemoveIndex(
            model_name='team',
            name='nfl_team_Name_a96ebf_idx',
        ),
        migrations.RemoveIndex(
            model_name='team',
            name='nfl_team_Key_2aa1a0_idx',
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['Owner'], name='nfl_contact_Owner_604eb2_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['Category'], name='nfl_contact_Categor_7d3ef8_idx'),
        ),
        migrations.AddIndex(
            model_name='playerdetail',
            index=models.Index(fields=['LastName', 'FirstName'], name='nfl_playerd_LastNam_5facad_idx'),
        ),
        migrations.AddIndex(
            model_name='playerdetail',
            index=models.Index(fields=['LastName'], name='nfl_playerd_LastNam_39d43c_idx'),
        ),
        migrations.AddIndex(
            model_name='playerdetail',
            index=models.Index(fields=['FirstName'], name='nfl_playerd_FirstNa_8e5277_idx'),
        ),
        migrations.AddIndex(
            model_name='stadium',
            index=models.Index(fields=['Name'], name='nfl_stadium_Name_4687db_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['Key'], name='nfl_team_Key_3938b0_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['Name'], name='nfl_team_Name_6ae581_idx'),
        ),
    ]
