# Generated by Django 4.2.4 on 2023-11-18 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0016_alter_contact_options_alter_playerdetail_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otherdetail',
            old_name='Number',
            new_name='Text',
        ),
    ]
