# Generated by Django 4.2.4 on 2023-12-07 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0018_ncaafplayer_ncaafteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ncaafteam',
            name='Active',
            field=models.BooleanField(default=True),
        ),
    ]
