# Generated by Django 4.2.4 on 2023-12-07 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0019_alter_ncaafteam_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ncaafplayer',
            name='GlobalTeamID',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ncaafplayer',
            name='Height',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ncaafplayer',
            name='Jersey',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ncaafplayer',
            name='TeamID',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ncaafplayer',
            name='Weight',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
