# Generated by Django 4.2.4 on 2024-01-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0022_playerpersonal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerpersonal',
            name='id',
        ),
        migrations.AlterField(
            model_name='playerpersonal',
            name='PlayerID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
