# Generated by Django 4.2.4 on 2024-01-24 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0024_alter_playerpersonal_playerid'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerFamilyContact',
            fields=[
                ('PlayerID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='nfl.playerdetail')),
                ('Address', models.CharField(max_length=200, null=True)),
                ('Phone', models.CharField(blank=True, max_length=20, null=True)),
                ('Email', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerMerchDesigner',
            fields=[
                ('PlayerID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='nfl.playerdetail')),
                ('Address', models.CharField(max_length=200, null=True)),
                ('Phone', models.CharField(blank=True, max_length=20, null=True)),
                ('Email', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerPersonalContact',
            fields=[
                ('PlayerID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='nfl.playerdetail')),
                ('Address', models.CharField(max_length=200, null=True)),
                ('Phone', models.CharField(blank=True, max_length=20, null=True)),
                ('Email', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerRespresentativeContact',
            fields=[
                ('PlayerID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='nfl.playerdetail')),
                ('Address', models.CharField(max_length=200, null=True)),
                ('Phone', models.CharField(blank=True, max_length=20, null=True)),
                ('Email', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerWorkContact',
            fields=[
                ('PlayerID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='nfl.playerdetail')),
                ('Address', models.CharField(max_length=200, null=True)),
                ('Phone', models.CharField(blank=True, max_length=20, null=True)),
                ('Email', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='PlayerPersonal',
            new_name='PlayerCompanyContact',
        ),
    ]
