# Generated by Django 4.2.4 on 2024-01-24 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0025_playerfamilycontact_playermerchdesigner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerworkcontact',
            name='PlayerID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='player_work', serialize=False, to='nfl.playerdetail'),
        ),
    ]
