# Generated by Django 4.2.4 on 2024-01-24 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0026_alter_playerworkcontact_playerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerpersonalcontact',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='playerworkcontact',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='playerpersonalcontact',
            name='PlayerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nfl.playerdetail'),
        ),
        migrations.AlterField(
            model_name='playerworkcontact',
            name='PlayerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nfl.playerdetail'),
        ),
    ]
