# Generated by Django 4.2.4 on 2024-01-24 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0027_playerpersonalcontact_id_playerworkcontact_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerpersonalcontact',
            name='id',
        ),
        migrations.RemoveField(
            model_name='playerworkcontact',
            name='id',
        ),
        migrations.AlterField(
            model_name='playerpersonalcontact',
            name='PlayerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='nfl.playerdetail'),
        ),
        migrations.AlterField(
            model_name='playerworkcontact',
            name='PlayerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='nfl.playerdetail'),
        ),
    ]
