# Generated by Django 4.2.4 on 2024-01-24 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0028_remove_playerpersonalcontact_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerfamilycontact',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playerfamilycontact',
            name='PlayerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nfl.playerdetail'),
        ),
    ]
