# Generated by Django 4.2.4 on 2024-01-24 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0029_playerfamilycontact_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerfamilycontact',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='playerfamilycontact',
            name='Phone',
        ),
        migrations.AddField(
            model_name='playerfamilycontact',
            name='Name',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='playerfamilycontact',
            name='Number',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AddField(
            model_name='playerfamilycontact',
            name='Relationship',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AlterField(
            model_name='playerfamilycontact',
            name='Email',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AlterField(
            model_name='playerfamilycontact',
            name='PlayerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nfl.playerdetail', unique=True),
        ),
    ]
