# Generated by Django 4.2.4 on 2024-01-24 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0030_remove_playerfamilycontact_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerfamilycontact',
            name='PlayerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nfl.playerdetail'),
        ),
    ]
