# Generated by Django 4.2.4 on 2024-01-25 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0031_alter_playerfamilycontact_playerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='playercompanycontact',
            name='Name',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='playerrespresentativecontact',
            name='Name',
            field=models.CharField(default='NA', max_length=50),
        ),
    ]
