# Generated by Django 4.2.4 on 2024-01-25 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0032_playercompanycontact_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerClubContact',
            fields=[
                ('PlayerID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='nfl.playerdetail')),
                ('Name', models.CharField(default='NA', max_length=50)),
                ('Address', models.CharField(max_length=200, null=True)),
                ('Phone', models.CharField(blank=True, max_length=20, null=True)),
                ('Email', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
